default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_jaguar_news_development
  username: root
  password: ""
  host: localhost
  port: 5432

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: blog_jaguar_news_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
