default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 

development:
  <<: *default
  ddatabase: blog_jaguar_news_development
  username: root
  password: ""
  host: localhost
  

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: blog_jaguar_news_production
  username: root
  password: ""
  host: localhost
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
 
