default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your_db_username
  password: your_db_password
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog_jaguar_development

test:
  <<: *default
  database: blog_jaguar_test

production:
  <<: *default
  database: blog_jaguar_production
